/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: g1VzAmryd8TFcSvE2eTVPY
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_6PhhmJpH54Dk } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6PHHMJpH54Dk/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_6PhhmJpH54Dk
});
